
language: node_js

node_js:
  - "6.11"

cache:
  - node_modules
  - src/node_modules

branches:
  only:
  - master

before_install:
  # Install in project to allow caching
  - npm install -g firebase-tools@^3.x
  - npm install -g typescript@^2.x

install:
  - cd src
  - npm install
  - cd ..

after_install:
  - tsc -p ./src

before_script:
  - firebase use $FIREBASE_PROJECT --token $FIREBASE_DEPLOY_KEY

script:
  # Set UNIFI related variables  
  - firebase functions:config:set unifi.username=$UNIFI_USERNAME --token $FIREBASE_DEPLOY_KEY
  - firebase functions:config:set unifi.password=$UNIFI_PASSWORD --token $FIREBASE_DEPLOY_KEY
  - firebase functions:config:set unifi.host=$UNIFI_HOST --token $FIREBASE_DEPLOY_KEY
  - firebase functions:config:set unifi.port=$UNIFI_PORT --token $FIREBASE_DEPLOY_KEY
  - firebase functions:config:set unifi.use_ssl=$UNIFI_USE_SSL --token $FIREBASE_DEPLOY_KEY 
  - firebase functions:config:set unifi.is_selfsigned=$UNIFI_SSL_SELF_SIGNED --token $FIREBASE_DEPLOY_KEY 
  - firebase functions:config:set unifi.redirect_url=$DEFAULT_REDIRECT_URL --token $FIREBASE_DEPLOY_KEY

  # Set Nexudus related variables
  - firebase functions:config:set nexudus.shortname=$NEXUDUS_SPACE_NAME --token $FIREBASE_DEPLOY_KEY

after_script:
  - firebase deploy -m "Travis build $TRAVIS_BUILD_NUMBER" --non-interactive --token $FIREBASE_DEPLOY_KEY
