sudo: required
services:
  - docker

branches:
  only:
  - master

before_script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build --rm -t kumpul/unifi-nexudus-hotspot .
- 
script:
- docker push kumpul/unifi-nexudus-hotspot